### ISSUE TITLE
框架可以只用在前端吗

### ISSUE THREAD

**Issue by weishaopeng** [robinleej/billund#1]
框架可以只用在前端吗？如果只用在前端会提高性能吗

**Comment by robinleej** [comment]
目前还需要依赖于node端。
但是以后的确是会有同时支持前端的想法的，因为有两种情况：
1：本地重构页面时
2：当node服务不可用时的降级方案

但这样的话，controler层就要比较注意，写的代码是需要同时支持两端的。

如果是为了性能考虑，node同构是更好的选择，因为渲染流程更短，首屏体验更好
